Bulletin_Board_MMORPG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [ path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

board/urls.py
from django.urls import path
from .views import (
    PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, CommentCreateView,
    UserCommentListView, CommentAcceptView, CommentDeleteView, subscriptions
)

app_name = 'board'

urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('<int:pk>', PostDetailView.as_view(), name='post-detail'),
    path('create/', PostCreateView.as_view(), name='post-create'),
    path('<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<int:pk>/comments/create/', CommentCreateView.as_view(), name='comment-create'),
    path('comments/', UserCommentListView.as_view(), name='comment-list'),
    path('comments/<int:pk>/accept/', CommentAcceptView.as_view(), name='comment-accept'),
    path('comments/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment-delete'),
    path('subscriptions/', subscriptions, name='subscriptions'),
]

board/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.urls import reverse
# Create your models here.

CATEGORY_CHOICES = [
    ('tanks', 'Танки'),
    ('healers', 'Хилы'),
    ('dd', 'ДД'),
    ('traders', 'Торговцы'),
    ('guildmasters', 'Гилдмастеры'),
    ('questgivers', 'Квестгиверы'),
    ('blacksmiths', 'Кузнецы'),
    ('leatherworkers', 'Кожевники'),
    ('alchemists', 'Зельевары'),
    ('spellmasters', 'Мастера заклинаний'),
]


class Category(models.Model):
    name = models.CharField(max_length=100, choices=CATEGORY_CHOICES, verbose_name='Категория')

    def __str__(self):
        return self.get_name_display()


class Subscription(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )


class Post(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    content_text = RichTextField(verbose_name='Контент')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Обновлено')


    def get_absolute_url(self):
        return reverse('board:post-detail', args=[str(self.id)])

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Объявление')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    content = models.TextField(verbose_name='Контент')  # Текст комментария
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    accepted = models.BooleanField(default=False, verbose_name='Принят')

    def __str__(self):
        return f'От {self.user.username} на "{self.post.title}"'

board/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content_text', 'category', 'user']

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) < 5 or len(title) > 100:
            raise forms.ValidationError('Заголовок должен быть от 5 до 100 символов.')
        return title


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content',]

    def __init__(self, *args, **kwargs):
        self.post_id = kwargs.pop('post_id', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.post_id = self.post_id
        if commit:
            instance.save()
        return instance

board/views.py
import logging
from smtplib import SMTPException
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy
from datetime import datetime
from .filters import PostFilter
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, DeleteView
)
from .forms import PostForm, CommentForm
from django.core.mail import send_mail
logger = logging.getLogger('django')
from .models import Subscription, Category, Post, Comment
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from django.db.models import Exists, OuterRef
import django_filters
class CommentFilter(django_filters.FilterSet):
    class Meta:
        model = Comment
        fields = ['post']

@login_required
@csrf_protect
def subscriptions(request):
    if request.method == 'POST':
        category_id = request.POST.get('category_id')
        category = get_object_or_404(Category, id=category_id)
        action = request.POST.get('action')

        if action == 'subscribe':
            Subscription.objects.get_or_create(user=request.user, category=category)
        elif action == 'unsubscribe':
            Subscription.objects.filter(user=request.user, category=category).delete()

    categories_with_subscriptions = Category.objects.annotate(
        user_subscribed=Exists(
            Subscription.objects.filter(
                user=request.user,
                category=OuterRef('pk'),
            )
        )
    ).order_by('name')

    return render(
        request,
        'subscriptions.html',
        {'categories': categories_with_subscriptions})





class UserCommentListView(PermissionRequiredMixin, ListView):
    permission_required = ('board.view_comment',)
    model = Comment
    template_name = 'board/user_comments.html'
    context_object_name = 'comments'

    def get_queryset(self):
        queryset = Comment.objects.filter(post__user=self.request.user)
        self.filterset = CommentFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context


class CommentAcceptView(PermissionRequiredMixin, UpdateView):
    permission_required = ('board.change_comment',)
    model = Comment
    fields = []
    template_name = 'board/comment_accept.html'

    def form_valid(self, form):
        comment = self.get_object()
        if not comment.accepted:  # Проверка состояния отклика
            comment.accepted = True
            comment.save()
            try:
                send_mail(
                    subject='Ваш отклик был принят',
                    message=f'Ваш отклик на объявление "{comment.post.title}" был принят.',
                    from_email='vitalivoloshin1975@yandex.co.il',
                    recipient_list=[comment.user.email],
                )
                logger.info("Email sent successfully")
            except SMTPException as e:
                logger.error(f"SMTPException: {e}")
            except Exception as e:
                logger.error(f"Exception: {e}")
        else:
            logger.info("Comment already accepted")
        return super().form_valid(form)

    def get_success_url(self):
        logger.info("Redirecting to comment list")
        return reverse_lazy('board:comment-list')



class CommentDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = ('board.delete_comment',)
    model = Comment
    template_name = 'board/comment_delete.html'
    success_url = reverse_lazy('board:user_comments')


class CommentCreateView(PermissionRequiredMixin, CreateView):
    permission_required = ('board.add_comment',)
    form_class = CommentForm
    model = Comment
    template_name = 'board/post_form.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['post_id'] = self.kwargs.get('pk')
        return kwargs

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.post_id = self.kwargs.get('pk')
        response = form.save()
        send_mail(
            subject='Новый отклик',
            message=f'Вы получили новый отклик: {response.content}',
            from_email='vitalivoloshin1975@yandex.co.il',
            recipient_list=[response.post.user.email],
        )
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('post-detail', kwargs={'pk': self.object.post.pk})



class PostListView(ListView):
    model = Post
    template_name = 'board/post_list.html'
    context_object_name = 'posts'
    ordering = ['-created_at']
    paginate_by = 1
    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = datetime.utcnow()
        return context


class PostDetailView(DetailView):
    model = Post
    template_name = 'board/post_detail.html'
    context_object_name = 'post'


class PostCreateView(PermissionRequiredMixin, CreateView):
    permission_required = ('board.add_post',)
    form_class = PostForm
    model = Post
    template_name = 'board/post_edit.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        response = form.save()
        send_mail(
            subject='Новое объявление',
            message=f'Вы получили новое объявление: {response.content_text}',
            from_email='vitalivoloshin1975@yandex.co.il',
            recipient_list=[response.user.email],
        )
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('board:post-detail', kwargs={'pk': self.object.pk})


class PostUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = ('board.change_post',)
    form_class = PostForm
    model = Post
    template_name = 'board/post_edit.html'


class PostDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = ('board.delete_post',)
    model = Post
    template_name = 'board/post_delete.html'
    success_url = reverse_lazy('board:post-list')

templates/board/comment_accept.html
{% extends 'base.html' %}
{% block content %}
    <h1>Принятие отклика</h1>
    <form method="post">
        {% csrf_token %}
        <p>Вы действительно хотите принять этот отклик?</p>
        <button type="submit" class="btn btn-primary">Принять</button>
    </form>
{% endblock %}

templates/board/comment_delete.html
<!-- templates/board/comment_delete.html -->
{% extends 'base.html' %}

{% block content %}
  <h2>Удалить отклик</h2>
  <form method="post">
    {% csrf_token %}
    <p>Вы уверены, что хотите удалить этот отклик?</p>
    <button type="submit">Удалить</button>
  </form>
{% endblock %}

templates/board/post_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1>Удаление поста</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

templates/board/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p>Автор: {{ post.user.username }}</p>
    <p>Категория: {{ post.category }}</p>
    <p>Дата создания: {{ post.created_at }}</p>
    <p>Дата обновления: {{ post.updated_at }}</p>
    <p>{{ post.content_text|safe }}</p>
{% endblock %}

templates/board/post_edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1>Редактирование поста</h1>
    <hr>
    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
    </form>
{% endblock content %}

templates/board/post_form.html
<!-- templates/board/response_form.html -->
{% extends 'base.html' %}

{% block content %}
  <h2>Откликнуться на объявление</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить отклик</button>
  </form>
{% endblock %}

templates/board/post_list.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% load custom_tags %}
{% block content %}
    <h1>Обьявления</h1>
    <h3>{% current_time '%b %d %Y' %}</h3>
    <form action="" method="get">
        {{ filterset.form.non_field_errors }}
        <label for="{{ filterset.form.title_icontains.id_for_label }}">Поиск:</label>
        <input
            id="{{ filterset.form.title_icontains.id }}"
            name="{{ filterset.form.title_icontains.name }}"
            value="{{ filterset.form.title_icontains.value }}"
            class="form-control">
        <button type="submit">Найти</button>
    </form>
    <hr>
    {% if perms.board.add_post %}
        <a href="{% url 'board:post-create' %}">Добавить обьявление</a>
    {% endif %}
    {% if perms.board.view_comment %}
        <a href="{% url 'board:comment-list' %}" class="btn btn-primary">Мои отклики</a>
    {% endif %}

    {% if posts %}
        <table>
            <tr>
                <td>Заголовок</td>
                <td>Текст</td>
                <td>Автор</td>
                <td>Категория</td>
                <td>Дата создания</td>
                <td>Дата обновления</td>
                {% if perms.board.change_post or perms.board.delete_post %}
                    <td>Действия</td>
                {% endif %}
            </tr>
            {% for post in posts %}
                <tr>
                    <td>{{ post.title }}</td>
                    <td>{{ post.content_text|safe|truncatechars:15 }}</td>
                    <td>{{ post.user.username }}</td>
                    <td>{{ post.category }}</td>
                    <td>{{ post.created_at }}</td>
                    <td>{{ post.updated_at }}</td>
                    <td>
                        {% if perms.board.change_post %}
                            <a href="{% url 'board:post-update' pk=post.id %}">Редактировать</a>
                        {% endif %}
                        {% if perms.board.delete_post %}
                            <a href="{% url 'board:post-delete' post.id %}">Удалить</a>
                        {% endif %}
                        <a href="{% url 'board:comment-create' post.pk %}">Откликнуться</a>
                    </td>
                </tr>

            {% empty %}
                <tr>
                    <td colspan="5">Отклики не найдены</td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>Обьявления не найдены</p>
    {% endif %}

    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}
{% endblock %}

templates/board/user_comments.html
{% extends 'base.html' %}
{% block content %}
    <form method="get">
        {{ filterset.form.as_p }}
        <button type="submit">Фильтровать</button>
    </form>
    <h1>Мои отклики</h1>
    {% if comments %}
        <table>
            <tr>
                <th>Обьявление</th>
                <th>Отклик</th>
                <th>Дата</th>
                <th>Статус</th>
                <th>Действия</th>
            </tr>
            {% for comment in comments %}
                <tr>
                    <td>{{ comment.post.title }}</td>
                    <td>{{ comment.content }}</td>
                    <td>{{ comment.created_at }}</td>
                    <td>{{ comment.get_status_display }}</td>
                    <td>
                        <a href="{% url 'board:comment-accept' pk=comment.id %}">Принять</a>
                        <a href="{% url 'board:comment-delete' pk=comment.id %}">Удалить</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>Нет откликов</p>
    {% endif %}
{% endblock %}